### ISSUE TITLE
phpp-fpm 7.2

### ISSUE THREAD

**Issue by phpwei** [sadok-f/php7fpm_vertica_odbc#3]
Is there a docker image of php-fpm7.2? I have rewritten it according to your dockerfile. It has not been successful. Recently, the project requires a minimum version of 7.1.3 for PHP. You need to connect to the vertica database.   Thank you

**Comment by sadok-f** [comment]
@phpwei thanks for reporting this issue.
I'll check it and update the repo.
7.2-fpm is there already, I need to update the latest version of Vertica client.
